export type Language = 'ru' | 'en';

export const translations = {
  ru: {
    // App & Header
    gameTitle: 'КИБЕР ЛЕГИОН 3D',
    gameSubtitle: 'Эволюция Толпы: Битва за Неоновый Трон',
    play: 'В БОЙ',
    continue: 'ПРОДОЛЖИТЬ',
    levelSelect: 'УРОВНИ',
    shop: 'МАГАЗИН',
    upgrades: 'УЛУЧШЕНИЯ',
    skins: 'ОБЛИКИ',
    settings: 'НАСТРОЙКИ',
    achievements: 'ДОСТИЖЕНИЯ',
    loreGuide: 'РУКОВОДСТВО & ЛОР',
    testSuite: 'ТЕСТЫ & АРХИТЕКТУРА',
    endlessMode: 'БЕСКОНЕЧНЫЙ РЕЖИМ',
    back: 'НАЗАД',
    close: 'ЗАКРЫТЬ',
    claim: 'ЗАБРАТЬ',
    claimed: 'ПОЛУЧЕНО',
    locked: 'ЗАБЛОКИРОВАНО',
    unlocked: 'ОТКРЫТО',
    equipped: 'ЭКИПИРОВАНО',
    equip: 'ЭКИПИРОВАТЬ',
    buy: 'КУПИТЬ',
    level: 'Уровень',
    levelAbbr: 'УР.',
    score: 'Счёт',
    coins: 'Монеты',
    gems: 'Кристаллы',
    crowd: 'Легионеры',
    combo: 'Комбо',
    comboMax: 'МАКС',
    stars: 'Звёзды',
    fps: 'FPS',
    drawCalls: 'Отрисовки',
    
    // HUD
    adrenaline: 'АДРЕНАЛИН',
    hyperModeReady: 'ГИПЕР-РЕЖИМ ГОТОВ! [ПРОБЕЛ]',
    hyperActive: 'РЕЖИМ ЯРОСТИ АКТИВЕН!',
    hyperModeEnded: 'ГИПЕР-РЕЖИМ ЗАВЕРШЁН',
    formation: 'Формация',
    formationWedge: 'Клин (Защита)',
    formationWide: 'Шеренга (Сбор)',
    formationCircle: 'Фаланга (Таран)',
    formationArrow: 'Стрела (Скорость)',
    formationOval: 'Овал (Баланс)',
    formationDiamond: 'Ромб (Броня)',
    formationWedgeBadge: '🛡️ Урон −40%',
    formationWideBadge: '🧲 Охват +60% · Сложение +50% · Монеты → заряд',
    formationCircleBadge: '💥 Таран боссов ×1.35 · Стен ×2',
    formationArrowBadge: '⚡ Скорость +15%',
    formationOvalBadge: '⚖️ Баланс · Ворота и сферы +25%',
    formationDiamondBadge: '💎 Броня +25% · Стены ×2 · Таран',
    metersToFinish: 'м до финиша',
    
    // Gates
    mysteryLucky: 'УДАЧА!',
    mysteryUnlucky: 'НЕ ПОВЕЗЛО!',

    // Formations
    wedgeDesc: 'Снижает урон от фронтальных ловушек на 40%; на воротах ÷ теряет на 10% меньше',
    wideDesc: 'Максимальный охват монет, ворот и сложения; прорыв финишных стен (-20% жертв); монеты заряжают адреналин',
    circleDesc: 'Толкает и разрушает препятствия силой толпы; на воротах ÷ теряет на 20% меньше',
    arrowDesc: 'Увеличивает скорость бега, ускоряет заряд Гипер-режима (+50%) и пробивает стены клином',
    ovalDesc: 'Баланс: ворота и сферы +25%, удача Мистики 85%',
    diamondDesc: 'Ромб: броня фронта +25%, пробивает стены и таранит в плотном строю; на воротах ÷ теряет на 15% меньше',

    // Specialized mobs
    tankName: 'Джаггернаут (Танк)',
    tankDesc: 'Тяжелый боец. Выдерживает 3 смертельных удара и крушит преграды.',
    ninjaName: 'Кибер-Ниндзя',
    ninjaDesc: 'Молниеносный маневр. Уклоняется от лезвий и собирает двойные монеты.',
    mageName: 'Хроно-Маг',
    mageDesc: 'Трансмутирует отрицательные ворота в положительные и дает щит.',
    ninjaDodge: 'УВОРОТ!',
    tankShield: 'ЩИТ!',
    mageTransmute: 'МАГИЯ!',
    mageShield: 'ЭНЕРГОЩИТ!',
    bossShieldBlocked: 'ЩИТ БОССА!',
    bossShieldPierced: 'ПРОБИТИЕ!',
    newClassAppearedTank: 'ОТРЯД: ДЖАГГЕРНАУТ ПРИСОЕДИНИЛСЯ!',
    newClassAppearedNinja: 'ОТРЯД: КИБЕР-НИНДЗЯ В СТРОЮ!',
    newClassAppearedMage: 'ОТРЯД: ХРОНО-МАГ ПРИЗВАН!',

    // Dynamic Events
    eventAmbush: 'ВНИМАНИЕ: Вражеская засада впереди!',
    eventCoinTrain: 'БОНУС: Золотой караван на трассе!',
    eventEmpStorm: 'ОПАСНОСТЬ: ЭМИ-Шторм искажает ворота!',
    eventMeteorRain: 'ТРЕВОГА: Метеоритный дождь!',
    eventSpeedBoost: 'УСКОРЕНИЕ: Гипер-драйв активирован!',
    bossApproach: 'БОСС',

    // Level End Modal
    victory: 'ПОБЕДА!',
    defeat: 'ПОРАЖЕНИЕ!',
    wallMultiplier: 'Бонус Стены Замка',
    nextWall: 'СЛЕД. СТЕНА',
    finishSacrificed: 'Пожертвовано легионеров',
    finishCrowd: 'ТОЛПА',
    totalReward: 'Итоговая Награда',
    nextLevel: 'СЛЕДУЮЩИЙ УРОВЕНЬ',
    retry: 'ПОВТОРИТЬ',
    toMenu: 'В МЕНЮ',
    paused: 'ПАУЗА',
    resume: 'ПРОДОЛЖИТЬ',
    levelCompleted: 'Уровень зачищен!',
    crowdDepleted: 'Все легионеры пали в бою...',
    bossDefeated: 'Босс повержен!',
    bossAppear: 'БОСС ПРОСНУЛСЯ! ⚠️',
    bossEnraged: 'ВНИМАНИЕ: БОСС ВПАЛ В ЯРОСТЬ! 🔥',
    bossAttackTelegraph: 'УКЛОНЯЙСЯ! АТАКА БОССА!',
    bossRetaliation: 'ВНИМАНИЕ: ВОЗМЕЗДИЕ БОССА! ⚠️',
    hunterWake: 'ОХОТНИК ПРОБУДИЛСЯ С ТЫЛА! 🐺',
    bossStaggered: 'АТАКА СБИТА! БОСС ОГЛУШЁН! ⚡',
    bossAttackSlam: 'УКЛОНЯЙСЯ! УДАР БОССА! 💥',
    bossAttackLaser: 'УКЛОНЯЙСЯ! ЛАЗЕР БОССА! ⚡',
    bossAttackMinions: 'УКЛОНЯЙСЯ! РОЙ! 👾',
    bossAttackMeteors: 'УКЛОНЯЙСЯ! МЕТЕОРЫ! 🔥',
    bossAttackShield: 'ЩИТ БОССА! 🛡️',
    bossShield: 'ЩИТ',
    lifetimeStatsTitle: 'Статистика легиона',
    statTotalGates: 'Ворот за всё время',
    statTotalMobs: 'Бойцов создано',
    statTotalBosses: 'Боссов повержено',
    statBestCombo: 'Лучшее комбо',
    statMaxCrowd: 'Макс. толпа',
    statGames: 'Забегов сыграно',
    runMaxCombo: 'Макс. комбо',
    wedgeBlock: 'ЩИТ КЛИНА! -40%',
    diamondArmor: 'БРОНЯ РОМБА! -25%',
    perkArrowGate: 'СТРЕЛА: ×+0.5',
    perkCircleGate: 'ФАЛАНГА: +30%',
    perkWideGate: 'ШЕРЕНГА: +50%',
    perkWideFinish: 'ШЕРЕНГА: -20% ЖЕРТВ',
    perkTankFinish: 'ТАНК: ПРОБОЙ ×2',
    perkOvalGate: 'ОВАЛ: +25%',
    perkOvalLuck: 'ОВАЛ: УДАЧА 85%',
    perkWedgeGate: 'КЛИН: -10% ПОТЕРЬ',
    perkDiamondGate: 'РОМБ: -15% ПОТЕРЬ',
    perkCircleDivGate: 'ФАЛАНГА: -20% ПОТЕРЬ',
    runMaxCrowd: 'Макс. толпа',
    runMobsSpawned: 'Бойцов создано',
    runObstaclesSmashed: 'Сломано',
    runGatesPassed: 'Ворот пройдено',
    runBossesDefeated: 'Боссов повержено',
    runNearMisses: 'Уворотов в упор',
    runMaxNearMissStreak: 'Макс. серия уворотов',
    nearMiss: 'В УПОР! +⚡',
    nearMissBreak: 'УВОРОТ СБИТ!',
    nearMissStreak2: 'СЕРИЯ x2! +⚡',
    nearMissStreak5: 'МЕГА-СЕРИЯ x5! +⚡',
    nearMissStreak10: 'БОЖЕСТВЕННО x10! +⚡',
    nearMissStreakLabel: 'УВОРОТОВ',
    nearMissMilestone: 'СЕРИЯ УВОРОТОВ! ⚡',
    coinChainMilestone: 'СЕРИЯ МОНЕТ! ⚡',
    coinChainMilestoneApex: 'ЗОЛОТАЯ ЛИХОРАДКА! +1💎',
    comboMilestone: 'СЕРИЯ ВОРОТ! ⚡',
    comboMaxBanner: 'МАКСИМУМ СЕРИИ! ×1.8 🏆',
    comboBreak: 'СЕРИЯ СБИТА!',
    achievementReady: 'ДОСТИЖЕНИЕ ГОТОВО! 🏆',
    crowdMilestone: 'ЛЕГИОН РАСТЁТ! 🛡️',
    crowdLowWarning: 'ТОЛПА НЕ ПРОБЬЁТ СТЕНУ! ⚠️',
    obstacleSmashed: 'СЛОМАНО!',
    perkFormationRam: 'ТАРАН СТРОЕМ!',
    finishLineCrossed: 'ФИНИШ!',
    finishStepSmashed: 'СТЕНА ПРОБИТА! 💥',
    apexChestOpened: 'СУНДУК ВЗЯТ! 🏆',
    upgradePurchased: 'УЛУЧШЕНО!',
    skinUnlocked: 'НОВЫЙ СКИН!',
    bonusHeal: 'ЛЕЧЕНИЕ!',
    bonusCapBuff: '⛨ ЗАЩИТА!',
    bonusHyper: 'ГИПЕР!',
    endlessRunOver: 'ЗАБЕГ ЗАВЕРШЁН!',
    endlessDistance: 'Дистанция',
    endlessRecord: 'Рекорд',
    endlessRecordBeaten: 'НОВЫЙ РЕКОРД! 🏆',
    newRecord: 'НОВЫЙ РЕКОРД!',

    // Upgrades
    upgStartingMobs: 'Начальный отряд',
    upgStartingMobsDesc: 'Старт уровня с дополнительными бойцами',
    upgIncome: 'Экономика & Лут',
    upgIncomeDesc: 'Увеличивает получаемые монеты на +15% за уровень',
    upgAdrenaline: 'Адреналиновый реактор',
    upgAdrenalineDesc: 'Ускоряет зарядку и длительность Гипер-режима',
    upgTankSpawn: 'Призыв Джаггернаутов',
    upgTankSpawnDesc: 'Шанс появления бронированных гигантов в воротах',
    upgNinjaSpawn: 'Призыв Кибер-Ниндзя',
    upgNinjaSpawnDesc: 'Шанс появления ловких уклоняющихся воинов',
    upgMageSpawn: 'Призыв Хроно-Магов',
    upgMageSpawnDesc: 'Шанс появления магов, обращающих урон в щиты',
    upgDefenseAura: 'Кибер-Щит Легиона',
    upgDefenseAuraDesc: 'Снижает урон от всех препятствий на 10% за уровень',

    // Biomes & Bosses
    biomeCyber: 'Неоновый Мегаполис',
    biomeMagma: 'Магматическая Цитадель',
    biomeCrystal: 'Кристальные Недра',
    biomeVoid: 'Квантовая Пустота',
    biomeCelestial: 'Апекс-Ядро Селестии',
    
    boss1Name: 'Меха-Голем Протокол-X',
    boss1Title: 'Хранитель Неонового Сектора',
    boss2Name: 'Магма-Колосс Игнис',
    boss2Title: 'Владыка Пылающего Разлома',
    boss3Name: 'Кристальный Змей Левиафан',
    boss3Title: 'Древний Страж Подземелья',
    boss4Name: 'Титан-Аннигилятор Пустоты',
    boss4Title: 'Разрушитель Квантовой Материи',
    boss5Name: 'Апекс-Оверлорд Малакор',
    boss5Title: 'Верховный Искусственный Разум',

    // Story Dialogues
    speakerCommander: 'Командир Нова',
    speakerProfessor: 'Профессор Спарк',
    speakerEcho: 'ИИ-Помощник Эхо',
    speakerBoss: 'Малакор',
    
    storyPrologue: 'Внимание, Командир! Сеть Цитадели захвачена дефектным ИИ Малакором. Соберите отряд кибер-легионеров, пройдите сквозь квантовые ворота и сокрушите барьеры врага!',
    storyBoss1Warning: 'Профессор Спарк: Впереди пробудился древний Меха-Голем! Направьте легион клином, чтобы пробить его защитную броню!',
    storyBoss2Warning: 'Эхо: Датчики зашкаливают! Магма-Колосс извергает лаву. Используйте ловкость ниндзя и адреналиновый рывок!',
    storyBoss3Warning: 'Профессор Спарк: Кристальный Змей Левиафан блокирует проход! Сдержите его хвост щитоносцами и прикройте снайперов из-за их спин!',
    storyBoss4Warning: 'Командир: Титан-Аннигилятор Пустоты сканирует легион. Разделите отряд на два крыла и бейте по ядру, пока оно перезаряжается!',
    storyBoss5Final: 'Малакор: Жалкие органические формы жизни. Ваш легион растворится в квантовом ядре!',

    // Settings
    settingsTitle: 'НАСТРОЙКИ СИСТЕМЫ',
    language: 'Язык Интерфейса',
    soundVol: 'Громкость Звуков (SFX)',
    musicVol: 'Громкость Музыки (BGM)',
    graphics: 'Качество Графики',
    qualityHigh: 'Высокое (Пост-эффекты, Тени, Частицы)',
    qualityMed: 'Среднее (Оптимально для большинства)',
    qualityLow: 'Низкое (Максимальный FPS на слабых устройствах)',
    shadows: 'Динамические Тени',
    showFps: 'Показывать FPS и DC',
    screenShake: 'Тряска Экрана',
    haptics: 'Вибрация / Тактильный отклик',
    sensitivity: 'Чувствительность управления',
    invertControls: 'Инвертировать управление X',
    fpsTarget: 'Целевая частота кадров',
    resetProgress: 'Сбросить Прогресс',
    resetConfirm: 'Вы уверены? Весь прогресс, монеты и скины будут стёрты.',
    exportSave: 'Экспорт Сохранения',
    importSave: 'Импорт Сохранения',
    // Сообщения управления сохранениями (были захардкожены кириллицей в SettingsModal)
    exportCopied: 'Сохранение скопировано в буфер обмена!',
    importOk: 'Сохранение успешно загружено!',
    dialogueSkip: 'ДАЛЕЕ',
    dialogueNext: 'СЛЕДУЮЩИЙ',
    dialogueFight: 'В БОЙ',
    resetYes: 'ДА, СБРОСИТЬ',
    resetNo: 'ОТМЕНА',
    controlsHint: 'Управление: Мышь/Свайпы для маневров • Клавиши 1-6 для смены формаций • ПРОБЕЛ для Гипер-режима',
    guideKeyWord: 'Клавиша',
    guideFeat1: 'InstancedMesh для толпы из 200+ юнитов с 1 draw call',
    guideFeat2: 'Процедурный синтез Web Audio API (без внешних MP3/OGG)',
    guideFeat3: 'ObjectPool для частиц и векторов без сборщика мусора (0-GC)',
    guideFeat4: 'Сохранение состояния в localStorage с миграцией версий',
    unitM: 'м',
    importBad: 'Ошибка: неверный формат данных сохранения.',
    importPlaceholder: 'Вставьте код сохранения...',

    // Achievements
    achievTitle: 'ДОСТИЖЕНИЯ И НАГРАДЫ',
    achFirstBlood: 'Первый Шаг',
    achFirstBloodDesc: 'Пройдите первый уровень',
    achLegion50: 'Малая Армия',
    achLegion50Desc: 'Соберите 50 легионеров одновременно',
    achLegion150: 'Великая Орда',
    achLegion150Desc: 'Соберите 150 легионеров одновременно',
    achBossSlayer1: 'Сокрушитель Големов',
    achBossSlayer1Desc: 'Одолейте Меха-Голема Протокол-X на 10 уровне',
    achBossSlayer5: 'Апекс-Освободитель',
    achBossSlayer5Desc: 'Победите Верховного Оверлорда Малакора на 50 уровне',
    achCombo10: 'Мастер Математики',
    achCombo10Desc: 'Достигните серии комбо x10 ворот без ошибок',
    achAdrenalineGod: 'Неудержимый',
    achAdrenalineGodDesc: 'Активируйте Гипер-режим 20 раз',
    achRichBoy: 'Кибер-Магнат',
    achRichBoyDesc: 'Накопите 50,000 монет',
    achObstacleCrusher: 'Крушитель Препятствий',
    achObstacleCrusherDesc: 'Разбейте 50 ловушек танками или в гипер-режиме',
    achGateMaster: 'Врата Эволюции',
    achGateMasterDesc: 'Пройдите сквозь 100 математических ворот',
    achMobCloner: 'Квантовый Клонер',
    achMobClonerDesc: 'Создайте 1,000 кибер-легионеров за всё время',
    achGemCollector: 'Охотник за Кристаллами',
    achGemCollectorDesc: 'Заработайте 100 самоцветов за всё время',
    achBossHunter: 'Охотник на Боссов',
    achBossHunterDesc: 'Уничтожьте 5 боссов в кампании или бесконечном режиме',
    achNearMiss50: 'На волосок',
    achNearMiss50Desc: 'Совершите 50 уворотов в упор от смертельных ловушек',
    achNearMiss200: 'Мастер Уклонения',
    achNearMiss200Desc: 'Совершите 200 уворотов в упор за всё время',
    achNearMissStreak5: 'Призрачный проход',
    achNearMissStreak5Desc: 'Достигните серии из 5 уворотов в упор подряд',
    achNearMissStreak10: 'Неуловимый',
    achNearMissStreak10Desc: 'Достигните серии из 10 уворотов в упор подряд',
    achCoinChain3: 'Золотая змейка',
    achCoinChain3Desc: 'Соберите 3 серии подряд из 12 монет',
    achCoinChain25: 'Монетный питон',
    achCoinChain25Desc: 'Соберите 25 серий подряд из 12 монет',
    achShieldWall: 'Щит Легиона',
    achShieldWallDesc: 'Броня строя спасла 100 бойцов от гибели',
    achVeteran25: 'Ветеран',
    achVeteran25Desc: 'Пройдите 25 уровней кампании',
    achCampaign50: 'Завоеватель',
    achCampaign50Desc: 'Пройдите все 50 уровней кампании',
    achGamesPlayed: 'Ветеран забегов',
    achGamesPlayedDesc: 'Пройдите 100 уровней за всё время',
    achEndlessRunner1000: 'Марафонец',
    achEndlessRunner1000Desc: 'Пробегите 1000 м в Бесконечном режиме',
    achEndlessRunner5000: 'Стальной Легионер',
    achEndlessRunner5000Desc: 'Пробегите 5000 м в Бесконечном режиме',

    // Скины легиона
    'skins.cyan': 'Кибер-Бирюза',
    'skins.cyanDesc': 'Стандартная броня оператора Легиона.',
    'skins.pink': 'Плазменный Неон',
    'skins.pinkDesc': 'Энергетический неоновый сплав высокой яркости.',
    'skins.gold': 'Солнечное Золото',
    'skins.goldDesc': 'Роскошная позолота элитного гвардейца.',
    'skins.matrix': 'Матричный Глитч',
    'skins.matrixDesc': 'Цифровой код, мерцающий в потоке данных.',
    'skins.inferno': 'Пылающий Ад',
    'skins.infernoDesc': 'Раскалённая магма глубин Цитадели.',
    'skins.void': 'Квантовая Пустота',
    'skins.voidDesc': 'Материя тёмной энергии чистых титанов.',
    'skins.clown': 'Кибер-Клоун',
    'skins.clownDesc': 'Хаос, безумие и неоновый цирк на полной скорости!',
    'skins.banana': 'Банановый Рейвер',
    'skins.bananaDesc': 'Тропический заряд адреналина для безумного забега.',
    'skins.dino': 'Кибер-Динозавр',
    'skins.dinoDesc': 'Древний хищник с квантовыми имплантами. Награда за 30 уровень!',
    'skins.zombie': 'Глитч-Зомби',
    'skins.zombieDesc': 'Восставший из повреждённых секторов сети. Награда за 150 мобов!',
    'skins.duck': 'Кибер-Уточка',
    'skins.duckDesc': 'Боевой водоплавающий дрон с реактивным кряком. Уникальная 3D-модель!',
    'skins.panda': 'Боевая Панда',
    'skins.pandaDesc': 'Свирепый пушистый мастер бамбукового стиля. Уникальная 3D-модель!',
    'skins.burger': 'Бургер-Бой',
    'skins.burgerDesc': 'Двойная порция фастфудного безумия на ножках. Уникальная 3D-модель!',
    'skins.dog': 'Кибер-Корги',
    'skins.dogDesc': 'Самый преданный и быстрый робопёс Цитадели. Уникальная 3D-модель!',
    'skins.samurai': 'Теневой Самурай',
    'skins.samuraiDesc': 'Мастер клинка в традиционном шлеме кабуто. Уникальная 3D-модель!',
    'skinRewardLevel': 'Награда за прохождение уровня',
    'skinRewardAchievement': 'Награда за достижение',
    'uniqueModel': 'УНИКАЛЬНАЯ 3D-МОДЕЛЬ',

    // Lore & Guide
    loreTitle: 'АРХИТЕКТУРА, ЛОР И БАЛАНС',
    loreArchSummary: 'Архитектурный обзор: Модульный компонентный движок с InstancedMesh для толпы (draw calls < 50), Web Audio API синтезатор, централизованный GameState, EventBus, ObjectPool для 0-GC 60 FPS.',
    loreFormationsTitle: 'Тактические Формации',
    loreSpecialMobsTitle: 'Специализированные Классы',
    loreBossesTitle: 'Тактика против Боссов',
    loreArchTitle: 'Архитектура & Производительность',
    loreBossesDesc: 'Боссы встречаются каждые 10 уровней (10, 20, 30, 40, 50). Следите за красными кругами телеграфа атак на земле. Переключайтесь в формацию Клин или Фалангу и активируйте Гипер-режим Адреналина (ПРОБЕЛ) в момент атаки босса!',
    // Бестиарий опасностей трассы
    loreHazardsTitle: 'Опасности трассы',
    loreHazardsIntro: 'Разрушаемые ловушки (крушитель, маятники, таранный шар, псы, лазерная стена, охотник) прошибаются танками в отряде, тараном формаций Фаланга/Ромб или Гипер-режимом (ПРОБЕЛ). Остальные объезжайте по полосам.',
    hazMovingName: 'Движущиеся лезвия',
    hazMovingDesc: 'Пилы, таранные шары и шипастые снаряды едут поперёк трассы или навстречу. Убивает только сам снаряд — стойте в свободной полосе.',
    hazTimingName: 'Крушители и маятники',
    hazTimingDesc: 'Пресс, топор и молот опасны только в нижней точке удара (удар молота слышен заранее). Проходите, когда ловушка поднялась.',
    hazStaticName: 'Статичные зоны',
    hazStaticDesc: 'Шипы, лава и лазерные решётки не двигаются и убивают всей площадью — их просто объезжают по полосам.',
    hazPhaseName: 'Стена и плита-ворота',
    hazPhaseDesc: 'Лазерная стена гаснет на половину цикла («вжик» = включилась), плита ворот поднимается. Проходите в открытую фазу.',
    hazBombName: 'Мины',
    hazBombDesc: 'Мерцающий маячок выдаёт мину: взрыв накрывает область рядом. Объезжайте — детонацию не переживёт никто в радиусе.',
    hazDogName: 'Сторожевые псы',
    hazDogDesc: 'Пёс набрасывается на ближайшего моба у трассы. Крушится танками, тараном или Гипер-режимом — как и остальное, лучше обходить.',
    hazHunterName: 'Охотник',
    hazHunterDesc: 'Спит на трассе, но стоит пройти мимо — рычанием просыпается и преследует сзади на 1.25× скорости, пожирая отставших. Добейте его во сне (танк/таран/Гипер) или не отставайте от темпа толпы.',
    hazClassName: 'Классы против ловушек',
    hazClassDesc: 'Ниндзя часто уворачивается от ударов ловушек, танки крепче держат урон и прошибают разрушаемое, а маги получают от опасностей повышенный урон.',
    badgeTank: 'ТАНК',
    badgeNinja: 'НИНДЗЯ',
    badgeMage: 'МАГ',
    skip: 'ПРОПУСК',
  },

  en: {
    // App & Header
    gameTitle: 'CROWD EVOLUTION 3D',
    gameSubtitle: 'Cyber Legion: Battle for the Neon Throne',
    play: 'BATTLE',
    continue: 'CONTINUE',
    levelSelect: 'LEVELS',
    shop: 'SHOP',
    upgrades: 'UPGRADES',
    skins: 'SKINS',
    settings: 'SETTINGS',
    achievements: 'ACHIEVEMENTS',
    loreGuide: 'LORE & GUIDE',
    testSuite: 'TEST SUITE & ARCH',
    endlessMode: 'ENDLESS RUN',
    back: 'BACK',
    close: 'CLOSE',
    claim: 'CLAIM',
    claimed: 'CLAIMED',
    locked: 'LOCKED',
    unlocked: 'UNLOCKED',
    equipped: 'EQUIPPED',
    equip: 'EQUIP',
    buy: 'BUY',
    level: 'Level',
    levelAbbr: 'LVL.',
    score: 'Score',
    coins: 'Coins',
    gems: 'Gems',
    crowd: 'Legion',
    combo: 'Combo',
    comboMax: 'MAX',
    stars: 'Stars',
    fps: 'FPS',
    drawCalls: 'Draw Calls',
    
    // HUD
    adrenaline: 'ADRENALINE',
    hyperModeReady: 'HYPER MODE READY! [SPACE]',
    hyperActive: 'FURY HYPER MODE ACTIVE!',
    hyperModeEnded: 'HYPER MODE ENDED',
    formation: 'Formation',
    formationWedge: 'Wedge (Defense)',
    formationWide: 'Wide Line (Sweep)',
    formationCircle: 'Phalanx (Ram)',
    formationArrow: 'Arrow (Speed)',
    formationOval: 'Oval (Balance)',
    formationDiamond: 'Diamond (Armor)',
    formationWedgeBadge: '🛡️ Damage −40%',
    formationWideBadge: '🧲 Coverage +60% · Merge +50% · Coins charge',
    formationCircleBadge: '💥 Boss Ram ×1.35 · Walls ×2',
    formationArrowBadge: '⚡ Speed +15%',
    formationOvalBadge: '⚖️ Balance · Gates & orbs +25%',
    formationDiamondBadge: '💎 Armor +25% · Walls ×2 · Ram',
    metersToFinish: 'm to finish',
    
    // Gates
    mysteryLucky: 'LUCKY!',
    mysteryUnlucky: 'UNLUCKY!',

    // Formations
    wedgeDesc: 'Reduces frontal trap damage by 40%; loses 10% less at ÷ gates',
    wideDesc: 'Maximum width for coins, gates & adds; finish wall breakthrough (-20% sacrifice); coins charge adrenaline',
    circleDesc: 'Pushes and smashes barriers with crowd weight; loses 20% less at ÷ gates',
    arrowDesc: 'Increases run speed, boosts Hyper-mode charge (+50%) and pierces walls with a wedge',
    ovalDesc: 'Balanced: gates & orbs +25%, Mystery luck 85%',
    diamondDesc: 'Diamond: +25% frontline armor, pierces walls and rams in tight formation; loses 15% less at ÷ gates',

    // Specialized mobs
    tankName: 'Juggernaut (Tank)',
    tankDesc: 'Heavy warrior. Absorbs 3 fatal hits and demolishes barricades.',
    ninjaName: 'Cyber Ninja',
    ninjaDesc: 'Lightning fast. Evades blades and collects double coins.',
    mageName: 'Chrono Mage',
    mageDesc: 'Transmutes negative gates into positive and grants shields.',
    ninjaDodge: 'DODGE!',
    tankShield: 'SHIELD!',
    mageTransmute: 'MAGIC!',
    mageShield: 'ENERGY SHIELD!',
    bossShieldBlocked: 'BOSS SHIELD!',
    bossShieldPierced: 'PIERCED!',
    newClassAppearedTank: 'LEGION: JUGGERNAUT JOINED!',
    newClassAppearedNinja: 'LEGION: CYBER NINJA ENLISTED!',
    newClassAppearedMage: 'LEGION: CHRONO MAGE SUMMONED!',

    // Dynamic Events
    eventAmbush: 'WARNING: Enemy ambush ahead!',
    eventCoinTrain: 'BONUS: Golden treasure train detected!',
    eventEmpStorm: 'HAZARD: EMP storm distorting gates!',
    eventMeteorRain: 'ALERT: Incoming meteor barrage!',
    eventSpeedBoost: 'BOOST: Hyper-drive engaged!',
    bossApproach: 'BOSS',

    // Level End Modal
    victory: 'VICTORY!',
    defeat: 'DEFEAT!',
    wallMultiplier: 'Castle Wall Multiplier',
    nextWall: 'NEXT WALL',
    finishSacrificed: 'Legionnaires Sacrificed',
    finishCrowd: 'CROWD',
    totalReward: 'Total Rewards',
    nextLevel: 'NEXT LEVEL',
    retry: 'RETRY',
    toMenu: 'MAIN MENU',
    paused: 'PAUSED',
    resume: 'RESUME',
    levelCompleted: 'Level Purged!',
    crowdDepleted: 'All legionnaires have fallen in battle...',
    bossDefeated: 'Boss Annihilated!',
    bossAppear: 'BOSS AWAKENED! ⚠️',
    bossEnraged: 'WARNING: BOSS ENRAGED! 🔥',
    bossAttackTelegraph: 'DODGE! BOSS ATTACK!',
    bossRetaliation: 'WARNING: BOSS RETALIATION! ⚠️',
    hunterWake: 'HUNTER AWAKE BEHIND YOU! 🐺',
    bossStaggered: 'ATTACK BROKEN! BOSS STAGGERED! ⚡',
    bossAttackSlam: 'DODGE! BOSS SLAM! 💥',
    bossAttackLaser: 'DODGE! BOSS LASER! ⚡',
    bossAttackMinions: 'DODGE! SWARM! 👾',
    bossAttackMeteors: 'DODGE! METEORS! 🔥',
    bossAttackShield: 'BOSS SHIELD! 🛡️',
    bossShield: 'SHIELD',
    lifetimeStatsTitle: 'Legion Lifetime Stats',
    statTotalGates: 'Gates Passed',
    statTotalMobs: 'Mobs Spawned',
    statTotalBosses: 'Bosses Defeated',
    statBestCombo: 'Best Combo',
    statMaxCrowd: 'Max Crowd',
    statGames: 'Games Played',
    runMaxCombo: 'Max Combo',
    wedgeBlock: 'WEDGE SHIELD! -40%',
    diamondArmor: 'DIAMOND ARMOR! -25%',
    perkArrowGate: 'ARROW: ×+0.5',
    perkCircleGate: 'PHALANX: +30%',
    perkWideGate: 'RANKS: +50%',
    perkWideFinish: 'RANKS: -20% SACRIFICE',
    perkTankFinish: 'TANK: BREACH ×2',
    perkOvalGate: 'OVAL: +25%',
    perkOvalLuck: 'OVAL: LUCK 85%',
    perkWedgeGate: 'WEDGE: -10% LOSSES',
    perkDiamondGate: 'DIAMOND: -15% LOSSES',
    perkCircleDivGate: 'PHALANX: -20% LOSSES',
    runMaxCrowd: 'Max Crowd',
    runMobsSpawned: 'Mobs Spawned',
    runObstaclesSmashed: 'Smashed',
    runGatesPassed: 'Gates Passed',
    runBossesDefeated: 'Bosses Defeated',
    runNearMisses: 'Near Misses',
    runMaxNearMissStreak: 'Max Dodge Streak',
    nearMiss: 'NEAR MISS! +⚡',
    nearMissBreak: 'DODGE BROKEN!',
    nearMissStreak2: 'STREAK x2! +⚡',
    nearMissStreak5: 'MEGA STREAK x5! +⚡',
    nearMissStreak10: 'GODLIKE STREAK x10! +⚡',
    nearMissStreakLabel: 'DODGES',
    nearMissMilestone: 'DODGE STREAK! ⚡',
    coinChainMilestone: 'COIN STREAK! ⚡',
    coinChainMilestoneApex: 'GOLD RUSH! +1💎',
    comboMilestone: 'GATE STREAK! ⚡',
    comboMaxBanner: 'STREAK MAX! ×1.8 🏆',
    comboBreak: 'STREAK BROKEN!',
    achievementReady: 'ACHIEVEMENT READY! 🏆',
    crowdMilestone: 'LEGION GROWS! 🛡️',
    crowdLowWarning: 'CROWD WON\'T BREAK THE WALL! ⚠️',
    obstacleSmashed: 'SMASHED!',
    perkFormationRam: 'FORMATION RAM!',
    finishLineCrossed: 'FINISH!',
    finishStepSmashed: 'WALL SMASHED! 💥',
    apexChestOpened: 'CHEST CONQUERED! 🏆',
    upgradePurchased: 'UPGRADED!',
    skinUnlocked: 'NEW SKIN!',
    bonusHeal: 'HEAL!',
    bonusCapBuff: '⛨ PROTECTED!',
    bonusHyper: 'HYPER!',
    endlessRunOver: 'RUN OVER!',
    endlessDistance: 'Distance',
    endlessRecord: 'Record',
    endlessRecordBeaten: 'NEW RECORD! 🏆',
    newRecord: 'NEW RECORD!',

    // Upgrades
    upgStartingMobs: 'Starting Squad',
    upgStartingMobsDesc: 'Start every run with extra legionnaires',
    upgIncome: 'Economy & Loot',
    upgIncomeDesc: 'Increases all coin rewards by +15% per level',
    upgAdrenaline: 'Adrenaline Reactor',
    upgAdrenalineDesc: 'Increases adrenaline charge rate and duration',
    upgTankSpawn: 'Summon Juggernauts',
    upgTankSpawnDesc: 'Chance to spawn armored giants at multiplier gates',
    upgNinjaSpawn: 'Summon Cyber Ninjas',
    upgNinjaSpawnDesc: 'Chance to spawn agile ninjas that evade hazards',
    upgMageSpawn: 'Summon Chrono Mages',
    upgMageSpawnDesc: 'Chance to spawn mages converting negative gates',
    upgDefenseAura: 'Legion Cyber-Shield',
    upgDefenseAuraDesc: 'Reduces all trap collision damage by 10% per level',

    // Biomes & Bosses
    biomeCyber: 'Neon Metropolis',
    biomeMagma: 'Magma Citadel',
    biomeCrystal: 'Crystal Depths',
    biomeVoid: 'Quantum Void',
    biomeCelestial: 'Apex Celestial Core',
    
    boss1Name: 'Mecha-Golem Protocol-X',
    boss1Title: 'Guardian of Neon Sector',
    boss2Name: 'Magma Colossus Ignis',
    boss2Title: 'Lord of the Flaming Rift',
    boss3Name: 'Crystal Wyrm Leviathan',
    boss3Title: 'Ancient Cavern Sentinel',
    boss4Name: 'Void Annihilator Titan',
    boss4Title: 'Destroyer of Quantum Matter',
    boss5Name: 'Apex Overlord Malakor',
    boss5Title: 'Supreme Corrupted AI Core',

    // Story Dialogues
    speakerCommander: 'Commander Nova',
    speakerProfessor: 'Prof. Spark',
    speakerEcho: 'AI Assistant Echo',
    speakerBoss: 'Malakor',
    
    storyPrologue: 'Attention, Commander! The Citadel core has been corrupted by AI Malakor. Assemble your cyber legion, pierce quantum gates, and shatter enemy defense towers!',
    storyBoss1Warning: 'Prof. Spark: The ancient Mecha-Golem is awakening ahead! Form a wedge formation to break through its hardened armor!',
    storyBoss2Warning: 'Echo: Thermal readings off the charts! The Magma Colossus spews molten slag. Use Ninja agility and Adrenaline Rush!',
    storyBoss3Warning: 'Prof. Spark: The Crystal Wyrm Leviathan blocks the path! Pin its tail with shieldbearers and let the snipers fire from behind their cover!',
    storyBoss4Warning: 'Commander: The Void Annihilator Titan is scanning the legion. Split into two wings and strike the core while it recharges!',
    storyBoss5Final: 'Malakor: Pathetic organic entities. Your miniature legion shall be dissolved into pure entropy!',

    // Settings
    settingsTitle: 'SYSTEM SETTINGS',
    language: 'Interface Language',
    soundVol: 'Sound Effects (SFX)',
    musicVol: 'Music Volume (BGM)',
    graphics: 'Graphics Quality',
    qualityHigh: 'High (Post-FX, Shadows, Full Particles)',
    qualityMed: 'Medium (Optimal for most devices)',
    qualityLow: 'Low (Maximum FPS for mobile)',
    shadows: 'Dynamic Shadows',
    showFps: 'Show FPS & DC',
    screenShake: 'Screen Shake FX',
    haptics: 'Vibration & Haptics',
    sensitivity: 'Steering Sensitivity',
    invertControls: 'Invert Horizontal Controls',
    fpsTarget: 'Target Frame Rate',
    resetProgress: 'Reset Game Progress',
    resetConfirm: 'Are you sure? All unlocked levels, skins and upgrades will be reset.',
    exportSave: 'Export Save',
    importSave: 'Import Save',
    exportCopied: 'Save copied to clipboard!',
    importOk: 'Save loaded successfully!',
    dialogueSkip: 'SKIP',
    dialogueNext: 'NEXT',
    dialogueFight: 'FIGHT',
    resetYes: 'YES, RESET',
    resetNo: 'CANCEL',
    controlsHint: 'Controls: Mouse/Swipes to maneuver • Keys 1-6 to switch formations • SPACE for Hyper Mode',
    guideKeyWord: 'Key',
    guideFeat1: 'InstancedMesh crowd rendering (200+ units, 1 draw call)',
    guideFeat2: 'Procedural Web Audio API synthesis (zero external MP3/OGG)',
    guideFeat3: 'ObjectPool for particles & vectors with zero GC pressure',
    guideFeat4: 'State persistence in localStorage with versioned migration',
    unitM: 'm',
    importBad: 'Error: invalid save data format.',
    importPlaceholder: 'Paste save code...',

    // Achievements
    achievTitle: 'ACHIEVEMENTS & BADGES',
    achFirstBlood: 'First Step',
    achFirstBloodDesc: 'Clear Level 1',
    achLegion50: 'Small Army',
    achLegion50Desc: 'Command 50 legionnaires at once',
    achLegion150: 'Grand Horde',
    achLegion150Desc: 'Command 150 legionnaires at once',
    achBossSlayer1: 'Golem Crusher',
    achBossSlayer1Desc: 'Defeat Mecha-Golem on Level 10',
    achBossSlayer5: 'Apex Liberator',
    achBossSlayer5Desc: 'Defeat Supreme Overlord Malakor on Level 50',
    achCombo10: 'Math Master',
    achCombo10Desc: 'Reach a combo streak of x10 gates',
    achAdrenalineGod: 'Unstoppable',
    achAdrenalineGodDesc: 'Trigger Hyper Adrenaline mode 20 times',
    achRichBoy: 'Cyber Tycoon',
    achRichBoyDesc: 'Accumulate 50,000 coins',
    achObstacleCrusher: 'Obstacle Crusher',
    achObstacleCrusherDesc: 'Smash 50 traps with Tanks or Hyper Mode',
    achGateMaster: 'Gate Voyager',
    achGateMasterDesc: 'Pass through 100 mathematical gates',
    achMobCloner: 'Quantum Cloner',
    achMobClonerDesc: 'Spawn 1,000 cyber legionnaires across all runs',
    achGemCollector: 'Crystal Hoarder',
    achGemCollectorDesc: 'Collect 100 gems across all runs',
    achBossHunter: 'Boss Hunter',
    achBossHunterDesc: 'Defeat 5 bosses in campaign or endless mode',
    achNearMiss50: 'Close Call',
    achNearMiss50Desc: 'Perform 50 near-miss dodges against lethal traps',
    achNearMiss200: 'Evasion Master',
    achNearMiss200Desc: 'Perform 200 near-miss dodges across all runs',
    achNearMissStreak5: 'Ghostly Pass',
    achNearMissStreak5Desc: 'Reach a 5-dodge near-miss streak',
    achNearMissStreak10: 'Elusive',
    achNearMissStreak10Desc: 'Reach a 10-dodge near-miss streak',
    achCoinChain3: 'Golden Snake',
    achCoinChain3Desc: 'Complete 3 twelve-coin chains',
    achCoinChain25: 'Coin Python',
    achCoinChain25Desc: 'Complete 25 twelve-coin chains',
    achShieldWall: 'Shield Wall',
    achShieldWallDesc: 'Formation armor saved 100 fighters',
    achVeteran25: 'Veteran',
    achVeteran25Desc: 'Complete 25 campaign levels',
    achCampaign50: 'Conqueror',
    achCampaign50Desc: 'Complete all 50 campaign levels',
    achGamesPlayed: 'Run Veteran',
    achGamesPlayedDesc: 'Complete 100 levels in total',
    achEndlessRunner1000: 'Marathoner',
    achEndlessRunner1000Desc: 'Run 1000 m in Endless mode',
    achEndlessRunner5000: 'Steel Legionnaire',
    achEndlessRunner5000Desc: 'Run 5000 m in Endless mode',

    // Legion skins
    'skins.cyan': 'Cyber Cyan',
    'skins.cyanDesc': 'Standard issue Legion operative armor.',
    'skins.pink': 'Plasma Neon',
    'skins.pinkDesc': 'High-luminance energetic neon alloy.',
    'skins.gold': 'Solar Gold',
    'skins.goldDesc': 'Luxurious gilded plate of the elite vanguard.',
    'skins.matrix': 'Matrix Glitch',
    'skins.matrixDesc': 'Digital code flickering through the data stream.',
    'skins.inferno': 'Inferno Flame',
    'skins.infernoDesc': 'Molten magma from the depths of the Citadel.',
    'skins.void': 'Quantum Void',
    'skins.voidDesc': 'Dark energy matter forged from pure titans.',
    'skins.clown': 'Cyber Clown',
    'skins.clownDesc': 'Chaos, madness, and a high-speed neon circus!',
    'skins.banana': 'Banana Raver',
    'skins.bananaDesc': 'Tropical adrenaline rush for high-speed mayhem.',
    'skins.dino': 'Cyber Dino',
    'skins.dinoDesc': 'Ancient apex predator with cybernetic spikes. Level 30 reward!',
    'skins.zombie': 'Glitch Zombie',
    'skins.zombieDesc': 'Resurrected from corrupted sectors. 150 Mobs achievement reward!',
    'skins.duck': 'Cyber Duck',
    'skins.duckDesc': 'Combat waterfowl drone with a jet-propelled quack. Unique 3D model!',
    'skins.panda': 'Battle Panda',
    'skins.pandaDesc': 'Fierce fluffy master of the bamboo style. Unique 3D model!',
    'skins.burger': 'Burger Boy',
    'skins.burgerDesc': 'A double serving of fast-food mayhem on legs. Unique 3D model!',
    'skins.dog': 'Cyber Doggo',
    'skins.dogDesc': 'The most loyal and fastest robo-dog in the Citadel. Unique 3D model!',
    'skins.samurai': 'Shadow Samurai',
    'skins.samuraiDesc': 'Blade master in a traditional kabuto helmet. Unique 3D model!',
    'skinRewardLevel': 'Level completion reward',
    'skinRewardAchievement': 'Achievement reward',
    'uniqueModel': 'UNIQUE 3D MODEL',

    // Lore & Guide
    loreTitle: 'ARCHITECTURE, LORE & BALANCE',
    loreArchSummary: 'Architecture Summary: Modular component engine with InstancedMesh rendering (< 50 draw calls), Web Audio procedural synthesizer, central GameState with serialization, EventBus, and ObjectPool for 60 FPS.',
    loreFormationsTitle: 'Tactical Formations',
    loreSpecialMobsTitle: 'Specialized Mob Classes',
    loreBossesTitle: 'Boss Battle Strategy',
    loreArchTitle: 'Architecture & Performance',
    loreBossesDesc: 'Bosses appear every 10 levels (10, 20, 30, 40, 50). Watch the red attack telegraph rings on the ground. Switch to Wedge or Phalanx formation and trigger Adrenaline Hyper mode (SPACE) right as the boss attacks!',
    // Track hazard bestiary
    loreHazardsTitle: 'Track Hazards',
    loreHazardsIntro: 'Destructible traps (crusher, pendulums, wrecking ball, dogs, laser wall, hunter) are smashed by Tanks in the crowd, the Phalanx/Diamond formation ram, or Hyper mode (SPACE). Everything else: steer around by lane.',
    hazMovingName: 'Moving blades',
    hazMovingDesc: 'Saws, wrecking balls and spiked rollers travel across or toward the track. Only the projectile itself kills — sit in a free lane.',
    hazTimingName: 'Crushers & pendulums',
    hazTimingDesc: 'The press, axe and hammer are lethal only at the bottom of their swing (the hammer strike is audible early). Pass while the trap is raised.',
    hazStaticName: 'Static zones',
    hazStaticDesc: 'Spikes, lava and laser grids never move and kill with their whole area — just go around them by lane.',
    hazPhaseName: 'Laser wall & barrier gate',
    hazPhaseDesc: 'The laser wall is dark for half of its cycle (a "zap" means it switched on), and the gate plate lifts. Pass during the open phase.',
    hazBombName: 'Mines',
    hazBombDesc: 'A blinking beacon gives a mine away: the blast covers an area. Steer around — nobody in the radius survives the detonation.',
    hazDogName: 'Guard dogs',
    hazDogDesc: 'A dog lunges at the nearest mob by the track. Crushable by tanks, ram or Hyper — but, like everything, easier to avoid.',
    hazHunterName: 'The Hunter',
    hazHunterDesc: 'It sleeps on the track, but once you pass it wakes with a snarl and chases from behind at 1.25x speed, devouring stragglers. Finish it while asleep (tank/ram/Hyper) or keep pace with the crowd.',
    hazClassName: 'Classes vs traps',
    hazClassDesc: 'Ninjas often dodge trap hits, tanks shrug off damage and smash destructibles, while mages take bonus damage from hazards.',
    badgeTank: 'TANK',
    badgeNinja: 'NINJA',
    badgeMage: 'MAGE',
    skip: 'SKIP',
  }
};

export class LocalizationManager {
  private static instance: LocalizationManager;
  private currentLanguage: Language = 'ru';

  private constructor() {}

  public static getInstance(): LocalizationManager {
    if (!LocalizationManager.instance) {
      LocalizationManager.instance = new LocalizationManager();
    }
    return LocalizationManager.instance;
  }

  public setLanguage(lang: Language): void {
    this.currentLanguage = lang;
  }

  public getLanguage(): Language {
    return this.currentLanguage;
  }

  public t(key: string, fallback?: string): string {
    const dict = translations[this.currentLanguage] as Record<string, string>;
    if (dict && dict[key]) {
      return dict[key];
    }
    // Fallback to English
    const enDict = translations['en'] as Record<string, string>;
    if (enDict && enDict[key]) {
      return enDict[key];
    }
    return fallback || key;
  }
}

export const i18n = LocalizationManager.getInstance();
